blank_issues_enabled: true
contact_links:
  - name: Documentation Issues
    url: https://github.com/benbjohnson/replicate.io/issues/new/choose
    about: Report documentation bugs or suggest improvements
  - name: Documentation
    url: https://replicate.io
    about: Check our documentation for setup and usage guides
